# Generated by Django 4.1 on 2022-10-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_bags_buyers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bags',
            new_name='bag',
        ),
        migrations.RenameModel(
            old_name='buyers',
            new_name='buyer',
        ),
    ]
