# Generated by Django 4.1 on 2022-10-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_bags_bag_rename_buyers_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
